modulythe:
    domain:
        validation:
            enabled: true
        events:
            async: true

    presentation:
        pagination:
            default-size: 20
            max-size: 100